name: unit-tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize] }
  push: { branches: [main] }
  schedule:
    - cron: "0 6 * * 6"

defaults:
  run:
    shell: bash --noprofile --norc -e -u -o pipefail {0}

jobs:
  tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    with:
      with_release_mode_testing: true
      with_coverage: true
      with_tsan: true
      warnings_as_errors: true
      with_linting: true
      with_windows: true
      with_wasm: true
      with_musl: true
      with_android: true
      extra_flags: "--explicit-target-dependency-import-check error --force-resolved-versions -Xswiftc -require-explicit-sendable"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
